@isTest
public class Test_Unit_OrderDecorator_1 {
    private static Order makeMockOrder() {
        return TestMockFactory.makeMockOrder();
    }

    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_1() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_2() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_3() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_4() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_5() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_6() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_7() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_8() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_9() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_10() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_11() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_12() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_13() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_14() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_15() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_16() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_17() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_18() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_19() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_20() {
        // ARRANGE
        Order o = makeMockOrder();

        // ACT
        OrderDecorator dec = new OrderDecorator(o);
        List<OrderItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
}
