@isTest
public class Test_E2E_LargeProductReads {
    private static final String PRICEBOOK_NAME = 'Large Product Reads';

    @TestSetup
    static void makeData() {
        TestFixtures.InsertProductsWithCustomPrices(PRICEBOOK_NAME);
    }

    @isTest
    static void readProducts_DoNothingElse_1() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_2() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_3() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_4() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_5() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_6() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_7() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_8() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_9() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_10() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }
    @isTest
    static void readProducts_DoNothingElse_11() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_12() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_13() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_14() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_15() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_16() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_17() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_18() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_19() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_20() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }
    @isTest
    static void readProducts_DoNothingElse_21() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_22() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_23() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_24() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_25() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_26() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_27() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_28() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_29() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_30() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }
    @isTest
    static void readProducts_DoNothingElse_31() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_32() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_33() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_34() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_35() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_36() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_37() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_38() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_39() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_40() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }
    @isTest
    static void readProducts_DoNothingElse_41() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_42() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_43() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_44() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_45() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_46() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_47() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_48() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_49() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }

    @isTest
    static void readProducts_DoNothingElse_50() {
        // ARRANGE
        List<Product2> prods = [SELECT Id FROM Product2];
        // ASSERT
        System.assertEquals([SELECT COUNT() FROM Product2], prods.size());
    }
}
