@isTest
public class Test_Unit_ServiceContractDecorator_2 {
    private static ServiceContract makeMockServiceContract() {
        return TestMockFactory.makeMockServiceContract();
    }

    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_1() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_2() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_3() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_4() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_5() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_6() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_7() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_8() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_9() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_10() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_11() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_12() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_13() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_14() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_15() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_16() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_17() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_18() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_19() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
    @isTest
    static void doSomething_JustDoIt_OutputMatchesInput_20() {
        // ARRANGE
        ServiceContract o = makeMockServiceContract();

        // ACT
        ServiceContractDecorator dec = new ServiceContractDecorator(o);
        List<ContractLineItem> ois = dec.doSomething(1000);

        // ASSERT
        System.assertEquals(1000, ois.size());
    }
}
